# Generated by Django 5.1.4 on 2025-01-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomnom_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes'),
        ),
    ]
